version: "3.8"

services:
  gateway-spring-cloud:
    image: homeacademy/gateway-spring-cloud
    environment:
      READER_URI: http://localhost:8085/
      WRITER_URI: http://localhost:8086/
    ports:
      - 8088:8088
    networks:
      - javelin

networks:
  javelin:
    external: false
    name: javelin
    driver: bridge
