version: "3.8"

services:
  test-reader-microservice:
    image: homeacademy/test-reader-microservice
    ports:
      - 8085:8085
    networks:
      - javelin

  gateway-spring-cloud:
    image: homeacademy/gateway-spring-cloud
#    Note that when you run app in Docker you should use host.docker.internal instead of localhost
    environment:
      READER_URI: http://host.docker.internal:8085
      WRITER_URI: http://host.docker.internal:8086
    ports:
      - 8088:8088
    networks:
      - javelin

networks:
  javelin:
    external: false
    name: javelin
    driver: bridge
