version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    networks:
      - javelin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
  writer-data-migration:
    depends_on:
      postgres:
        condition: service_healthy
    image: homeacademy/writer-data-migration:javelin_0.0.1-SNAPSHOT
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?user=postgres&password=password
    ports:
      - 5001:5001
    networks:
      - javelin
  writer:
    image: homeacademy/writer:javelin_0.0.1-SNAPSHOT
    depends_on:
      writer-data-migration:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    ports:
      - 8080:8080
    networks:
      - javelin

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  javelin:
    external: false
    name: javelin
    driver: bridge
